# Generated by Django 5.2.4 on 2025-08-04 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='F.I.SH')),
                ('position', models.CharField(max_length=100, verbose_name='Lavozim')),
                ('company_name', models.CharField(max_length=255, verbose_name='Kompaniya nomi')),
                ('website', models.CharField(blank=True, null=True, verbose_name='Sayt manzili')),
                ('legal_address', models.TextField(verbose_name='Yuridik manzil')),
                ('marketplace_brand', models.CharField(max_length=255, verbose_name='Marketplace-lardagi brendi')),
                ('annual_order_volume', models.CharField(max_length=100, verbose_name='Yillik buyurtmalar hajmi')),
                ('segment', models.CharField(max_length=100, verbose_name='Segment')),
                ('cooperation_terms', models.CharField(max_length=100, verbose_name='Hamkorlik shartlari (Incoterms)')),
                ('payment_terms', models.CharField(max_length=100, verbose_name='To‘lov shartlari')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Buyurtmachi',
                'verbose_name_plural': 'Buyurtmachilar',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Kompaniya nomi')),
                ('market_experience', models.CharField(max_length=100, verbose_name='Bozor tajribasi')),
                ('full_name', models.CharField(max_length=255, verbose_name='F.I.SH')),
                ('position', models.CharField(max_length=100, verbose_name='Lavozim')),
                ('min_order_quantity', models.CharField(max_length=100, verbose_name='Minimal buyurtma hajmi')),
                ('product_segment', models.CharField(max_length=100, verbose_name='Maxsulot segmenti')),
                ('commercial_offer_text', models.TextField(verbose_name='Tijorat taklifi')),
                ('commercial_offer', models.FileField(blank=True, null=True, upload_to='offers/', verbose_name='Tijorat taklifi fayl')),
                ('production_address', models.TextField(verbose_name='Ishlab chiqarish manzili')),
                ('office_address', models.TextField(verbose_name='Ofis manzili')),
                ('website', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sayt manzili')),
                ('has_quality_control', models.BooleanField(default=False, verbose_name='Sifat nazorati mavjudmi')),
                ('has_crm', models.BooleanField(default=False, verbose_name='CRM tizimi mavjudmi ')),
                ('has_erp', models.BooleanField(default=False, verbose_name='ERP tizimi mavjudmi')),
                ('has_gemini_gerber', models.BooleanField(default=False, verbose_name='Gemini/Gerber mavjudmi')),
                ('employee_count', models.IntegerField(verbose_name='Hodimlar soni')),
                ('owns_building', models.BooleanField(verbose_name='Bino o‘zlariniki yoki ijaradami')),
                ('has_power_issues', models.BooleanField(verbose_name='Elektr/gaz uzilishlari bormi')),
                ('has_credit_load', models.BooleanField(verbose_name='Kredit yuki mavjudmi')),
                ('organization_structure', models.TextField(verbose_name='Tashkilot tuzilmasi')),
                ('equipment_info', models.TextField(verbose_name="Uskunalar haqida ma'lumot")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Ishlab chiqaruvchi',
                'verbose_name_plural': 'Ishlab chiqaruvchilar',
            },
        ),
    ]
