# Generated by Django 5.2.4 on 2025-08-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cooperation_terms',
            field=models.CharField(max_length=250, verbose_name='Hamkorlik shartlari (Incoterms)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='payment_terms',
            field=models.CharField(max_length=250, verbose_name='To‘lov shartlari'),
        ),
    ]
