# Generated by Django 5.2.4 on 2025-08-26 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_customer_cooperation_terms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='offers/', verbose_name='Sertificat'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
