# Generated by Django 5.2.4 on 2025-08-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_customer_phone_manufacturer_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='status',
            field=models.CharField(choices=[('in_progress', 'Jarayonda'), ('approved', 'Tasdiqlandi'), ('paid', 'To‘lov qilindi')], default='in_progress', max_length=20, verbose_name='Holat'),
        ),
    ]
