# Generated by Django 5.2.4 on 2025-08-26 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_additionalservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationAdditionalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'Jarayonda'), ('approved', 'Tasdiqlandi'), ('paid', 'To‘lov qilindi')], default='in_progress', max_length=20, verbose_name='Holat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='application.manufacturer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='application.additionalservice')),
            ],
            options={
                'verbose_name': 'Qo‘shimcha xizmat arizasi',
                'verbose_name_plural': 'Qo‘shimcha xizmat arizalari',
                'unique_together': {('manufacturer', 'service')},
            },
        ),
    ]
