# Generated by Django 5.2.4 on 2025-08-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_applicationadditionalservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=128, verbose_name='Phone number')),
                ('contact_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='Contact ID')),
                ('deal_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='Deal ID')),
            ],
            options={
                'verbose_name': 'Temporary contact',
                'verbose_name_plural': 'Temporary contacts',
            },
        ),
    ]
