# Generated by Django 5.2.4 on 2025-08-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_temporarycontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarycontact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
