# Generated by Django 5.2.4 on 2025-08-28 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_temporarycontact_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('telegram_username', models.CharField(blank=True, max_length=150, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application.botuser', verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application.botuser', verbose_name='Foydalanuvchi'),
        ),
    ]
