# Generated by Django 5.2.4 on 2025-08-28 21:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_botuser_alter_customer_user_alter_manufacturer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botuser',
            old_name='telegram_username',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='botuser',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='botuser',
            name='is_bot',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='botuser',
            name='language_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='botuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='botuser',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
