# Generated by Django 5.2.4 on 2025-08-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_rename_telegram_username_botuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalservice',
            options={'ordering': ['order'], 'verbose_name': "Qo'shimcha xizmat", 'verbose_name_plural': "Qo'shimcha xizmatlar"},
        ),
        migrations.AddField(
            model_name='additionalservice',
            name='is_apply',
            field=models.BooleanField(default=False, verbose_name="Qo'llab-quvvatlanadi"),
        ),
        migrations.AddField(
            model_name='additionalservice',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Tartib raqami'),
        ),
        migrations.AddField(
            model_name='additionalservice',
            name='type',
            field=models.CharField(choices=[('manufacturer', 'Ishlab chiqaruvchi'), ('customer', 'Buyurtmachi')], default='customer', max_length=20),
        ),
        migrations.AddField(
            model_name='botuser',
            name='type',
            field=models.CharField(choices=[('manufacturer', 'Ishlab chiqaruvchi'), ('customer', 'Buyurtmachi')], default='customer', max_length=20),
        ),
    ]
