# Generated by Django 5.2.4 on 2025-09-01 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_alter_additionalservice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='total_orders',
            field=models.IntegerField(default=0, verbose_name='Jami buyurtmalar'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='payment_terms',
            field=models.CharField(max_length=250, verbose_name="To'lov shartlari"),
        ),
    ]
