# Generated by Django 5.2.4 on 2025-09-01 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_customer_total_orders_alter_customer_payment_terms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalservice',
            name='is_apply',
        ),
        migrations.CreateModel(
            name='UserApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.additionalservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.botuser')),
            ],
            options={
                'default_related_name': 'applied_service',
            },
        ),
    ]
