# Generated by Django 5.2.4 on 2025-09-01 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_remove_additionalservice_is_apply_userapply'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalservice',
            name='payment_type',
            field=models.CharField(choices=[('one_time', "1 martalik to'lov"), ('monthly', "Oylik to'lov")], default='one_time', max_length=20, verbose_name="To'lov turi"),
        ),
        migrations.AlterField(
            model_name='additionalservice',
            name='type',
            field=models.CharField(choices=[('customer', 'Customer'), ('manufacturer', 'Manufacturer')], default='customer'),
        ),
    ]
