# Generated by Django 5.2.4 on 2025-09-01 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_additionalservice_payment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalservice',
            name='type',
            field=models.CharField(choices=[('manufacturer', 'Ishlab chiqaruvchi'), ('customer', 'Buyurtmachi')], default='customer', max_length=20),
        ),
    ]
