# Generated by Django 5.2.4 on 2025-09-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_alter_additionalservice_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalservice',
            name='payment_type',
            field=models.CharField(choices=[('one_time', "1 martalik to'lov"), ('monthly', "Oylik to'lov")], default='one_time', max_length=20),
        ),
    ]
