# Generated by Django 5.2.4 on 2025-09-01 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_alter_additionalservice_payment_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'default_related_name': 'customers', 'verbose_name': 'Buyurtmachi', 'verbose_name_plural': 'Buyurtmachilar'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'default_related_name': 'manufacturers', 'verbose_name': 'Ishlab chiqaruvchi', 'verbose_name_plural': 'Ishlab chiqaruvchilar'},
        ),
    ]
