# Generated by Django 5.2.4 on 2025-09-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_alter_customer_options_alter_manufacturer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
    ]
