# Generated by Django 5.2.4 on 2025-09-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0018_botuser_is_active_alter_botuser_is_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalservice',
            name='option',
            field=models.CharField(choices=[('video_review', 'Video sharh'), ('invite_manager', 'Sotuv menejerini taklif qilish'), ('training_reps', 'ROPlarni o‘qitish'), ('place_order', 'Buyurtma joylashtirish'), ('select_factory', 'Fabrika tanlash'), ('online_b2b', 'Online B2B'), ('custom_order', 'Tur buyurtma')], default='video_review', max_length=100),
        ),
        migrations.AlterField(
            model_name='additionalservice',
            name='type',
            field=models.CharField(choices=[('customer', 'Customer'), ('manufacturer', 'Manufacturer')], default='customer', max_length=20),
        ),
    ]
