# Generated by Django 5.2.4 on 2025-09-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0020_slider"),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacturer",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Tartib raqami"),
        ),
    ]
