# Generated by Django 5.2.4 on 2025-09-05 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0021_manufacturer_order"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ApplicationAdditionalService",
            new_name="Application",
        ),
    ]
