# Generated by Django 5.2.4 on 2025-09-05 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0022_rename_applicationadditionalservice_application"),
    ]

    operations = []
