# Generated by Django 5.2.4 on 2025-09-05 06:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0023_auto_20250905_0615"),
    ]

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "banner",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="packages/",
                        verbose_name="Баннер",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("start", "Старт - Базовый пакет"),
                            ("growth", "Рост - Продвинутый пакет"),
                            ("export", "Экспорт - Максимальный пакет"),
                        ],
                        default="start",
                        max_length=20,
                        verbose_name="Тип пакета",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Пакет",
                "verbose_name_plural": "Пакеты",
            },
        ),
        migrations.AlterModelOptions(
            name="additionalservice",
            options={
                "ordering": ["order"],
                "verbose_name": "Дополнительная услуга",
                "verbose_name_plural": "Дополнительные услуги",
            },
        ),
        migrations.AlterModelOptions(
            name="application",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
            },
        ),
        migrations.AlterModelOptions(
            name="customer",
            options={
                "default_related_name": "customers",
                "verbose_name": "Заказчик",
                "verbose_name_plural": "Заказчики",
            },
        ),
        migrations.AlterModelOptions(
            name="manufacturer",
            options={
                "default_related_name": "manufacturers",
                "verbose_name": "Производитель",
                "verbose_name_plural": "Производители",
            },
        ),
        migrations.AlterModelOptions(
            name="slider",
            options={"verbose_name": "Слайдер", "verbose_name_plural": "Слайдеры"},
        ),
        migrations.AlterModelOptions(
            name="temporarycontact",
            options={
                "verbose_name": "Временный контакт",
                "verbose_name_plural": "Временные контакты",
            },
        ),
        migrations.AlterModelOptions(
            name="userapply",
            options={
                "default_related_name": "applied_service",
                "verbose_name": "Заявка пользователя",
                "verbose_name_plural": "Заявки пользователей",
            },
        ),
        migrations.AlterUniqueTogether(
            name="application",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="application",
            name="additional_notes",
            field=models.TextField(
                blank=True, null=True, verbose_name="Дополнительная информация"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="budget_estimated_price",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Бюджет или примерная цена",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="contact_email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email адрес"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="contact_phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Контактный телефон"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="application.customer",
                verbose_name="Заказчик",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="interested_factories",
            field=models.TextField(
                blank=True, null=True, verbose_name="Какие фабрики интересуют"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="needs_tourist_program",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Нужна ли туристическая программа",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="order_volume",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Объем заказа"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="planned_arrival_dates",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="В каких датах планируется приезд",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="planned_stay_days",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Сколько дней планируется пребывание",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="product_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Описание продукта"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="production_delivery_time",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Срок производства и доставки",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="quantity_to_see",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Какое количество хотелось бы посмотреть",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="segment",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Сегмент"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="segment_category",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Сегмент/категория"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="special_requirements",
            field=models.TextField(
                blank=True, null=True, verbose_name="Специальные требования"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AddField(
            model_name="application",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="application.botuser",
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="work_purpose",
            field=models.TextField(blank=True, null=True, verbose_name="Цель труда"),
        ),
        migrations.AlterField(
            model_name="additionalservice",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="additionalservice",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="additionalservice",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AlterField(
            model_name="additionalservice",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="additionalservice",
            name="option",
            field=models.CharField(
                choices=[
                    ("video_review", "Видео обзор"),
                    ("invite_manager", "Пригласить менеджера по продажам"),
                    ("training_reps", "Обучение представителей"),
                    ("place_order", "Размещение заказа"),
                    ("select_factory", "Выбор фабрики"),
                    ("online_b2b", "Онлайн B2B"),
                    ("custom_order", "Тур заказ"),
                ],
                default="video_review",
                max_length=100,
                verbose_name="Опция",
            ),
        ),
        migrations.AlterField(
            model_name="additionalservice",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Порядковый номер"),
        ),
        migrations.AlterField(
            model_name="additionalservice",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("one_time", "Одноразовая оплата"),
                    ("monthly", "Ежемесячная оплата"),
                ],
                default="one_time",
                max_length=20,
                verbose_name="Тип оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="additionalservice",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Цена"
            ),
        ),
        migrations.AlterField(
            model_name="additionalservice",
            name="type",
            field=models.CharField(
                choices=[("customer", "Customer"), ("manufacturer", "Manufacturer")],
                default="customer",
                max_length=20,
                verbose_name="Тип",
            ),
        ),
        migrations.AlterField(
            model_name="additionalservice",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="application",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="manufacturer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="application.manufacturer",
                verbose_name="Производитель",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="application.additionalservice",
                verbose_name="Услуга",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "В процессе"),
                    ("approved", "Одобрено"),
                    ("paid", "Оплачено"),
                    ("rejected", "Отклонено"),
                ],
                default="in_progress",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="botuser",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="botuser",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Имя"
            ),
        ),
        migrations.AlterField(
            model_name="botuser",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AlterField(
            model_name="botuser",
            name="is_bot",
            field=models.BooleanField(default=False, verbose_name="Бот"),
        ),
        migrations.AlterField(
            model_name="botuser",
            name="language_code",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Код языка"
            ),
        ),
        migrations.AlterField(
            model_name="botuser",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Фамилия"
            ),
        ),
        migrations.AlterField(
            model_name="botuser",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Номер телефона"
            ),
        ),
        migrations.AlterField(
            model_name="botuser",
            name="telegram_id",
            field=models.BigIntegerField(
                blank=True, null=True, unique=True, verbose_name="Telegram ID"
            ),
        ),
        migrations.AlterField(
            model_name="botuser",
            name="type",
            field=models.CharField(
                choices=[("manufacturer", "Производитель"), ("customer", "Заказчик")],
                default="customer",
                max_length=20,
                verbose_name="Тип пользователя",
            ),
        ),
        migrations.AlterField(
            model_name="botuser",
            name="username",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Имя пользователя"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="annual_order_volume",
            field=models.CharField(
                max_length=100, verbose_name="Годовой объем заказов"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="company_name",
            field=models.CharField(max_length=255, verbose_name="Название компании"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="cooperation_terms",
            field=models.CharField(
                max_length=250, verbose_name="Условия сотрудничества (Incoterms)"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="full_name",
            field=models.CharField(max_length=255, verbose_name="Ф.И.О"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="legal_address",
            field=models.TextField(verbose_name="Юридический адрес"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="marketplace_brand",
            field=models.CharField(
                max_length=255, verbose_name="Бренд на маркетплейсах"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="payment_terms",
            field=models.CharField(max_length=250, verbose_name="Условия оплаты"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Телефон"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="position",
            field=models.CharField(max_length=100, verbose_name="Должность"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="segment",
            field=models.CharField(max_length=100, verbose_name="Сегмент"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="total_orders",
            field=models.IntegerField(default=0, verbose_name="Всего заказов"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="application.botuser",
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="website",
            field=models.CharField(blank=True, null=True, verbose_name="Адрес сайта"),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="certificate",
            field=models.FileField(
                blank=True, null=True, upload_to="offers/", verbose_name="Сертификат"
            ),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="commercial_offer",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="offers/",
                verbose_name="Файл коммерческого предложения",
            ),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="commercial_offer_text",
            field=models.TextField(verbose_name="Коммерческое предложение"),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="company_name",
            field=models.CharField(max_length=255, verbose_name="Название компании"),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="employee_count",
            field=models.IntegerField(verbose_name="Количество сотрудников"),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="equipment_info",
            field=models.TextField(verbose_name="Информация об оборудовании"),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="full_name",
            field=models.CharField(max_length=255, verbose_name="Ф.И.О"),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="has_credit_load",
            field=models.BooleanField(verbose_name="Есть ли кредитная нагрузка"),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="has_crm",
            field=models.BooleanField(
                default=False, verbose_name="Есть ли CRM система"
            ),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="has_erp",
            field=models.BooleanField(
                default=False, verbose_name="Есть ли ERP система"
            ),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="has_gemini_gerber",
            field=models.BooleanField(
                default=False, verbose_name="Есть ли Gemini/Gerber"
            ),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="has_power_issues",
            field=models.BooleanField(
                verbose_name="Есть ли проблемы с электричеством/газом"
            ),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="has_quality_control",
            field=models.BooleanField(
                default=False, verbose_name="Есть ли контроль качества"
            ),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="market_experience",
            field=models.CharField(max_length=100, verbose_name="Опыт на рынке"),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="min_order_quantity",
            field=models.CharField(
                max_length=100, verbose_name="Минимальный объем заказа"
            ),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="office_address",
            field=models.TextField(verbose_name="Офисный адрес"),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Порядковый номер"),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="organization_structure",
            field=models.TextField(verbose_name="Организационная структура"),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="owns_building",
            field=models.BooleanField(
                verbose_name="Здание собственное или арендованное"
            ),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="phone",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Телефон"
            ),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="position",
            field=models.CharField(max_length=100, verbose_name="Должность"),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="product_segment",
            field=models.CharField(max_length=100, verbose_name="Сегмент продукции"),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="production_address",
            field=models.TextField(verbose_name="Адрес производства"),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "В процессе"),
                    ("approved", "Одобрено"),
                    ("paid", "Оплачено"),
                ],
                default="in_progress",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="application.botuser",
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="website",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Адрес сайта"
            ),
        ),
        migrations.AlterField(
            model_name="slider",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="slider",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="slider",
            name="image",
            field=models.ImageField(upload_to="sliders/", verbose_name="Изображение"),
        ),
        migrations.AlterField(
            model_name="slider",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AlterField(
            model_name="slider",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Заголовок"),
        ),
        migrations.AlterField(
            model_name="slider",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="temporarycontact",
            name="contact_id",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="ID контакта"
            ),
        ),
        migrations.AlterField(
            model_name="temporarycontact",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="temporarycontact",
            name="deal_id",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="ID сделки"
            ),
        ),
        migrations.AlterField(
            model_name="temporarycontact",
            name="phone_number",
            field=models.CharField(max_length=128, verbose_name="Номер телефона"),
        ),
        migrations.AlterField(
            model_name="userapply",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="application.additionalservice",
                verbose_name="Услуга",
            ),
        ),
        migrations.AlterField(
            model_name="userapply",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="application.botuser",
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="application.package",
                verbose_name="Пакет",
            ),
        ),
        migrations.CreateModel(
            name="PackageItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="application.package",
                        verbose_name="Пакет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Услуга пакета",
                "verbose_name_plural": "Услуги пакетов",
            },
        ),
    ]
