# Generated by Django 5.2.4 on 2025-09-05 06:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0024_package_alter_additionalservice_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AddField(
            model_name="manufacturer",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AddField(
            model_name="packageitem",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата создания"
            ),
        ),
        migrations.AddField(
            model_name="packageitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AddField(
            model_name="temporarycontact",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AddField(
            model_name="userapply",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата создания"
            ),
        ),
        migrations.AddField(
            model_name="userapply",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="additionalservice",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="slider",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="temporarycontact",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата создания"
            ),
        ),
    ]
