# Generated by Django 5.2.4 on 2025-09-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0025_customer_updated_at_manufacturer_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Порядковый номер"),
        ),
        migrations.AddField(
            model_name="packageitem",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Порядковый номер"),
        ),
    ]
