# Generated by Django 5.2.4 on 2025-09-05 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0026_package_order_packageitem_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="botuser",
            options={
                "verbose_name": "Пользователь бота",
                "verbose_name_plural": "Пользователи бота",
            },
        ),
    ]
