# Generated by Django 5.2.4 on 2025-09-08 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0027_alter_botuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'default_related_name': 'applications', 'ordering': ['-created_at'], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='packageitem',
            options={'default_related_name': 'package_items', 'verbose_name': 'Услуга пакета', 'verbose_name_plural': 'Услуги пакетов'},
        ),
        migrations.RemoveField(
            model_name='package',
            name='type',
        ),
        migrations.AddField(
            model_name='package',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='slider',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядковый номер'),
        ),
    ]
