# Generated by Django 5.2.4 on 2025-09-05 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0027_alter_botuser_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="application",
            options={
                "default_related_name": "applications",
                "ordering": ["-created_at"],
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
            },
        ),
        migrations.AlterModelOptions(
            name="packageitem",
            options={
                "default_related_name": "package_items",
                "verbose_name": "Услуга пакета",
                "verbose_name_plural": "Услуги пакетов",
            },
        ),
    ]
