# Generated by Django 5.2.4 on 2025-09-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0028_alter_application_options_alter_packageitem_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="package",
            name="type",
        ),
        migrations.AddField(
            model_name="package",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="slider",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Порядковый номер"),
        ),
    ]
