# Generated by Django 5.2.4 on 2025-09-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0028_alter_application_options_alter_packageitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядковый номер'),
        ),
    ]
