# Generated by Django 5.2.4 on 2025-09-08 11:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0028_alter_application_options_alter_packageitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('chosen', 'Выбран'), ('not_chosen', 'Не выбран')], default='not_chosen', max_length=20, verbose_name='Статус')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.application')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.customer')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.manufacturer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.additionalservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.botuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оффер',
                'verbose_name_plural': 'Офферы',
            },
        ),
    ]
