# Generated by Django 5.2.4 on 2025-09-08 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0029_add_slider_order_and_package_description"),
    ]

    operations = []
