# Generated by Django 5.2.4 on 2025-09-21 20:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0029_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='product_segment',
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='product_segment',
            field=models.ManyToManyField(to='application.segment', verbose_name='Сегмент продукции'),
        ),
    ]
