# Generated by Django 5.2.4 on 2025-09-08 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0030_merge_20250908_0401"),
    ]

    operations = [
        migrations.AddField(
            model_name="slider",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Порядковый номер"),
        ),
    ]
