# Generated by Django 5.2.4 on 2025-09-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0030_segment_remove_manufacturer_product_segment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='segment',
            options={'verbose_name': 'Сегмент', 'verbose_name_plural': 'Сегмент'},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='segment',
        ),
        migrations.AddField(
            model_name='customer',
            name='segment',
            field=models.ManyToManyField(to='application.segment', verbose_name='Сегмент'),
        ),
    ]
