# Generated by Django 5.2.4 on 2025-10-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0031_alter_segment_options_remove_customer_segment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="additionalservice",
            name="offerta_file",
            field=models.FileField(
                blank=True, null=True, upload_to="offerta/", verbose_name="Файл оферты"
            ),
        ),
    ]
