# Generated by Django 5.2.4 on 2025-10-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0032_additionalservice_offerta_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="company_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Название компании"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="full_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Ф.И.О"
            ),
        ),
    ]
