# Generated by Django 5.2.4 on 2025-10-01 09:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0033_application_company_name_application_full_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManufacturerSertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "certificate",
                    models.FileField(
                        upload_to="certificates/", verbose_name="Сертификат"
                    ),
                ),
                (
                    "certificate_received_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата получения сертификата"
                    ),
                ),
                (
                    "certificate_expiration_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата истечения сертификата"
                    ),
                ),
            ],
            options={
                "verbose_name": "Сертификат производителя",
                "verbose_name_plural": "Сертификаты производителей",
                "default_related_name": "manufacturer_certificates",
            },
        ),
        migrations.RemoveField(
            model_name="manufacturer",
            name="certificate",
        ),
        migrations.AddField(
            model_name="application",
            name="execution_terms",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Сроки исполнения"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="looking_for_production",
            field=models.TextField(
                blank=True, null=True, verbose_name="Ищу производство"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="manufacturer_requirements",
            field=models.TextField(
                blank=True, null=True, verbose_name="Требование к производителю"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="payment_terms",
            field=models.TextField(
                blank=True, null=True, verbose_name="Условия оплаты"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="sample_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="samples/", verbose_name="Фото образца"
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="contact_manager",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Контактный менеджер",
            ),
        ),
    ]
