# Generated by Django 5.2.4 on 2025-10-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0034_manufacturersertificate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacturer",
            name="sertificates",
            field=models.ManyToManyField(
                blank=True,
                to="application.manufacturersertificate",
                verbose_name="Сертификаты",
            ),
        ),
    ]
