# Generated by Django 5.2.4 on 2025-10-15 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0035_manufacturer_sertificates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='annual_order_volume',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cooperation_terms',
        ),
        migrations.AlterField(
            model_name='additionalservice',
            name='payment_type',
            field=models.CharField(choices=[('free', 'Бесплатно'), ('one_time', 'Одноразовая оплата'), ('monthly', 'Ежемесячная оплата')], default='one_time', max_length=20, verbose_name='Тип оплаты'),
        ),
    ]
