# Generated by Django 5.2.4 on 2025-10-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0036_remove_customer_annual_order_volume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='status',
            field=models.CharField(choices=[('in_progress', 'В процессе'), ('approved', 'Одобрено'), ('paid', 'Оплачено'), ('canceled', 'Отменено')], default='in_progress', max_length=20, verbose_name='Статус'),
        ),
    ]
