# Generated by Django 5.2.4 on 2025-10-23 17:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0037_alter_manufacturer_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturerCompanyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('image', models.ImageField(upload_to='company_images/', verbose_name='Изображение компании')),
            ],
            options={
                'verbose_name': 'Изображение компании',
                'verbose_name_plural': 'Изображения компании',
                'default_related_name': 'manufacturer_company_image',
            },
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Логотип компании'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='company_images',
            field=models.ManyToManyField(blank=True, to='application.manufacturercompanyimage', verbose_name='Изображение компании'),
        ),
    ]
