# Generated by Django 5.2.4 on 2025-10-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0038_manufacturercompanyimage_manufacturer_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='company_images',
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='images',
            field=models.ManyToManyField(blank=True, to='application.manufacturercompanyimage', verbose_name='Изображения'),
        ),
    ]
