# Generated by Django 5.2.4 on 2025-10-24 19:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0039_remove_manufacturer_company_images_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=100, verbose_name='Имя оператора')),
                ('phone_number', models.CharField(max_length=25, unique=True, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Контактный номер оператора',
                'verbose_name_plural': 'Контактные номера операторов',
            },
        ),
    ]
