# Generated by Django 5.2.4 on 2025-10-15 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0036_remove_customer_annual_order_volume_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('paylov', 'Paylov'), ('payme', 'Payme'), ('click', 'Click UP')], default='paylov', max_length=15)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='waiting', max_length=15)),
                ('amount', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('payment_url', models.CharField(blank=True, max_length=512, null=True)),
                ('reference', models.TextField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=512, null=True)),
                ('is_paid_with_card', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('extra', models.JSONField(blank=True, null=True)),
                ('additional_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.additionalservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='application.botuser')),
            ],
        ),
    ]
